-- Script de Criação de Tabela e Políticas de Segurança (Supabase)
-- Este arquivo deve ser executado no SQL Editor do Supabase para inicializar o banco de dados do projeto.

-- 1. Criação da tabela de equipamentos
create table equipamentos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  setor bigint not null
);

-- 2. Habilitação de RLS (Row Level Security) para segurança
alter table equipamentos enable row level security;

-- 3. Políticas de acesso público para operações de CRUD (Leitura, Inserção, Atualização e Exclusão)
create policy "Permitir leitura pública" on equipamentos 
  for select using (true);

create policy "Permitir inserção pública" on equipamentos 
  for insert with check (true);

create policy "Permitir atualização pública" on equipamentos 
  for update using (true);

create policy "Permitir exclusão pública" on equipamentos 
  for delete using (true);
